var found = true;
var grade = 88.7;
var firstName = "Reski";
var lastName = "Ahmad";
console.log(found);
console.log("The Grade is", grade);
console.log("The Grade is" + grade);
console.log("The Firsname is", firstName);
console.log("The Last Name is", lastName);
console.log("Boleean", found);
